if [ -f "${HOME}/.local/share/dot-configs/apollo/current/generated/zsh-colors.zsh" ]; then
  source "${HOME}/.local/share/dot-configs/apollo/current/generated/zsh-colors.zsh"
else
  APOLLO_PROMPT_ACCENT=''
  APOLLO_PROMPT_INFO=''
  APOLLO_PROMPT_SUCCESS=''
  APOLLO_PROMPT_DANGER=''
  APOLLO_PROMPT_TEXT=''
  APOLLO_PROMPT_MUTED=''
  APOLLO_PROMPT_RESET=''
fi

PROMPT="${APOLLO_PROMPT_ACCENT}%n${APOLLO_PROMPT_MUTED}@${APOLLO_PROMPT_INFO}%m ${APOLLO_PROMPT_TEXT}%~ ${APOLLO_PROMPT_ACCENT}❯${APOLLO_PROMPT_RESET} "
ZSH_THEME_GIT_PROMPT_PREFIX=" ${APOLLO_PROMPT_MUTED}git:${APOLLO_PROMPT_INFO}"
ZSH_THEME_GIT_PROMPT_SUFFIX="${APOLLO_PROMPT_RESET}"
ZSH_THEME_GIT_PROMPT_DIRTY="${APOLLO_PROMPT_DANGER}*${APOLLO_PROMPT_RESET}"
ZSH_THEME_GIT_PROMPT_CLEAN="${APOLLO_PROMPT_SUCCESS}+${APOLLO_PROMPT_RESET}"
PROMPT="${PROMPT% }\$(git_prompt_info) "
RPROMPT=''
